# Generated by Django 4.0.3 on 2022-03-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative text'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to='images/', verbose_name='image'),
        ),
    ]
